# class ConnectionErrorException(Exception()):
#     __init__(self):
#         print('bad connection')